sudo: required
services:
  - docker


before_install:
  - docker build -t aaniket/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aaniket/docker-react npm run test -- --coverage --watchAll=false